apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  # this lables are replicaset labels
  labels:
    project: roboshop
    tier: backend
    component: cart
spec:
  replicas: 1
  selector:
      # using this lables replicaset will select the pods.
    matchLabels:
      project: roboshop
      tier: backend
      component: cart
      # this is pod definiton pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: cart
    spec:
      containers:
      - name: cart
        image: surendra3207/cart:1.1.0
        imagePullPolicy: Always # safe to pull every time there may be images with same version rebuilt and push
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 2
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 2
        envFrom:
        - configMapRef:
            name: cart

---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart
spec:
  type : NodePort
  selector:
    project: roboshop
    tier: backend
    component: cart
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
