apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  # this lables are replicaset labels
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  replicas: 1
  selector:
      # using this lables replicaset will select the pods.
    matchLabels:
      project: roboshop
      tier: db
      component: rabbitmq
      # this is pod definiton pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: surendra3207/rabbitmq:1.0.0
        envFrom:
        - configMapRef:
            name: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    tier: db
    component: rabbitmq
spec:
  type : NodePort
  selector:
    project: roboshop
    tier: db
    component: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
