apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # this lables are replicaset labels
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  replicas: 1
  selector:
      # using this lables replicaset will select the pods.
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
      # this is pod definiton pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: surendra3207/catalogue:1.0.0
        envFrom:
        - configMapRef:
          name: catalogue  
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  type : NodePort
  selector:
    project: roboshop
    tier: backend
    component: catalogue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
